# Generated by Django 4.2.16 on 2024-09-11 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otp_app', '0002_alter_usermodel_managers_usermodel_is_admin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='otp_enabled',
            new_name='otp_validated',
        ),
    ]
