# Generated by Django 4.2.16 on 2024-09-12 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp_app', '0003_rename_otp_enabled_usermodel_otp_validated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='name',
            new_name='second_name',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='is_admin',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='age',
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='blood_type',
            field=models.CharField(choices=[('I', 'First'), ('II', 'second'), ('III', 'third'), ('IV', 'fourth')], default=False, max_length=10),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
    ]
