# Generated by Django 4.2.16 on 2024-09-16 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp_app', '0004_rename_name_usermodel_second_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='first_name',
            field=models.CharField(default=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='last_name',
            field=models.CharField(default=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='second_name',
            field=models.CharField(default=False, max_length=50),
        ),
    ]
