# Generated by Django 4.2.16 on 2024-09-29 15:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp_app', '0005_alter_usermodel_first_name_alter_usermodel_last_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='otp_validated',
            new_name='otp_mode',
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(16)]),
        ),
    ]
